client_id = "db8ae39bef889270d9cfd2d8349ff8fe"
name = "FileJar"
handle = "filejar"
application_url = "https://app.filejar.com"
embedded = true

[build]
dev_store_url = "filejar.myshopify.com"
include_config_on_deploy = true

[access.admin]
direct_api_mode = "offline"
embedded_app_direct_api_access = true

[access_scopes]
scopes = "read_products,write_products"

[auth]
redirect_urls = [ ]

[webhooks]
api_version = "2024-10"

[[webhooks.subscriptions]]
topics = ["app/uninstalled"]
compliance_topics = ["customers/data_request", "customers/redact", "shop/redact"]
uri = "https://app.filejar.com/api/webhooks"

[app_proxy]
url = "https://app.filejar.com/api/proxy"
subpath = "filejar"
prefix = "apps"

[pos]
embedded = false