# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "ff3aece5bf4701517ca65c31eb69043b"
name = "FileJar STAGING"
handle = "filejar-staging"
application_url = "https://filejar-git-staging-traian-s-personal-projects.vercel.app"
embedded = true

[build]
dev_store_url = "filejar.myshopify.com"
include_config_on_deploy = true

[access.admin]
direct_api_mode = "offline"
embedded_app_direct_api_access = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_products,write_products,read_orders,read_assigned_fulfillment_orders,write_assigned_fulfillment_orders,read_merchant_managed_fulfillment_orders,write_merchant_managed_fulfillment_orders"

[auth]
redirect_urls = [ ]

[webhooks]
api_version = "2024-10"

  [[webhooks.subscriptions]]
  topics = [
  "app/uninstalled",
  "orders/paid",
  "orders/cancelled",
  "orders/updated",
  "orders/fulfilled",
  "orders/partially_fulfilled",
  "orders/risk_assessment_changed"
]
  compliance_topics = [ "customers/data_request", "customers/redact", "shop/redact" ]
  uri = "https://filejar-git-staging-traian-s-personal-projects.vercel.app/api/webhooks"

[app_proxy]
url = "https://filejar-git-staging-traian-s-personal-projects.vercel.app/api/proxy"
subpath = "filejar-staging"
prefix = "apps"

[pos]
embedded = false
