# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "b1b3d94f1ab2e55605a54a00f5e711aa"
name = "FileJar DEV"
handle = "filejar-dev"
application_url = "https://filejar.ngrok.dev"
embedded = true

[auth]
redirect_urls = [ ]

[build]
dev_store_url = "filejar.myshopify.com"
include_config_on_deploy = true

[access.admin]
direct_api_mode = "offline"
embedded_app_direct_api_access = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_products,write_products"

[webhooks]
api_version = "2024-10"

  [[webhooks.subscriptions]]
  topics = [ "app/uninstalled" ]
  compliance_topics = [ "customers/data_request", "customers/redact", "shop/redact" ]
  uri = "https://filejar.ngrok.dev/api/webhooks"

[app_proxy]
url = "https://filejar.ngrok.dev/api/proxy"
subpath = "filejar-dev"
prefix = "apps"

[pos]
embedded = false
