api_version = "2024-10"

[[extensions]]
name = "FileJar"
handle = "filejar"
type = "ui_extension"

[extensions.capabilities]
network_access = true

[[extensions.targeting]]
module = "./src/ThankYouBlock.jsx"
target = "purchase.thank-you.block.render"
export = "thankYouBlock"

[[extensions.targeting]]
module = "./src/OrderStatusBlock.jsx"
target = "customer-account.order-status.block.render"
export = "orderDetailsBlock"
