export const billingPlans = [
  {
    id: "free", // it's important that the free plan has the id "free" and that it exists
    name: "Free",
    description: "Everything you need to get started.",
    benefits: ["500MB of storage", "30 orders every month", "5 digital products", "Unlimited files"],
    price: "Free",
    totalStorage: 524288000,
    totalFiles: -1,
    totalOrders: 30,
    totalProducts: 5,
    totalBandwidth: -1,
  },
  {
    id: "basic",
    name: "Basic",
    description: "Up your game with more storage, more orders, unlimited products, and more.",
    benefits: ["25GB of storage", "250 orders every month", "Unlimited figital products", "Unlimited files", "No extra charges"],
    amount: 9.99,
    trialDays: 14,
    totalStorage: 26843545600,
    totalBandwidth: -1,
    totalFiles: -1,
    totalOrders: 250,
    totalProducts: -1,
  },
  {
    id: "pro",
    name: "Pro",
    description: "Most popular plan for stores in your tier, with unlimited orders, products, and files.",
    benefits: ["250GB of storage", "Unlimited orders", "Unlimited digital products", "Unlimited files", "No extra charges"],
    amount: 19.99,
    trialDays: 14,
    recommended: true,
    totalStorage: 268435456000,
    totalBandwidth: -1,
    totalFiles: -1,
    totalOrders: -1,
    totalProducts: -1,
  },
  {
    id: "enterprise",
    name: "Enterprise",
    description: "For large stores with high storage needs. Priority support included.",
    benefits: ["2,500GB of storage", "Unlimited orders", "Unlimited digital products", "Unlimited files", "No extra charges", "Priority support"],
    amount: 49.99,
    trialDays: 14,
    totalStorage: 2684354560000,
    totalBandwidth: -1,
    totalFiles: -1,
    totalOrders: -1,
    totalProducts: -1,
  },
];
